name: 'bookstore-spring-boot-microservices-course'
services:
  catalog-db:
    image: mysql:8.3.0
    container_name: catalog-db # Sets the actual container's name to catalog-db (otherwise Docker auto-generates a name).

    environment:
      - MYSQL_ROOT_PASSWORD=mani
      - MYSQL_DATABASE=catalogdb
      - MYSQL_USER=cataloguser
      - MYSQL_PASSWORD=catalogpass
    ports:
      - "15432:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmani"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m