name: Catalog Service

on:
  push:
    paths:
      - catalog/**
    branches:
      - 'main'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with maven
        run: ./mvnw -ntp verify   #runs tests and checks that the build is valid and everything works before installing/deploying.


          